In [26]:
import pandas as pd
import requests
import io

In [27]:
url = 'https://gtnh.miraheze.org/wiki/IC2_Crops_List'
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

In [28]:
# tables = pd.read_html(url)

In [29]:
response = requests.get(url, headers=headers)

In [30]:
tables = pd.read_html(io.StringIO(response.text))

In [32]:
tables[0]

,Name,Discovered By,Seed,Drops,Tier,Attributes,Growth Stages,GS After Harvest,Relative Speed,Internal Name,Notes
0,Aurelia,IC2 Team,NaN,Aurelia Leaves (for Gold),8,"Gold, Leaves, Metal",5,2,Stages 1-3: 750 Stage 4: 2200,aurelia,Requires Gold Ore (Vanilla) or Block of Gold u...
1,Blackthorn,Alblaka,NaN,Ink Sac,2,"Black, Flower, Rose",4,3,Stages 1-2: 400 Stage 3: 600,blackthorn,Light level of at least 12.
2,Brown Mushroom,IC2 Team,NaN,Mushroom (Brown),2,"Brown, Food, Mushroom",3,1,Stages 1-2: 200,Brown Mushrooms,Must be hydrated.
3,Carrots,IC2 Team,Carrots,Carrots,2,"Orange, Food, Carrots",3,1,Stages 1-2: 400,carrots,Light level of at least 12.
4,Cocoa,Notch,Cocoa,Cocoa,3,"Brown, Food, Stem",4,3,Stages 1-2: 400 Stage 3: 900,cocoa,Nutrients of at least 3.
5,Coffee,Snoochy,Coffee Beans,Coffee Beans,7,"Leaves, Ingredient, Beans",5,3,Stages 1-2: 1400 Stage 3: 700 Stage 4: 2100,coffee,"Light level of at least 9. Can be ""harvested"" ..."
6,Cyazint,Alblaka,NaN,Cyan Dye,2,"Blue, Flower",4,3,Stages 1-2: 400 Stage 3: 600,cyazint,Light level of at least 12.
7,Cyprium,IC2 Team,NaN,Tiny Pile of Copper Dust,6,"Orange, Leaves, Metal",4,2,Stages 1-2: 800 Stage 3: 2000,cyprium,Requires Copper Block underneath farm block to...
8,Dandelion,Notch,Dandelionx4,Dandelion Yellow,2,"Yellow, Flower",4,3,Stages 1-2: 400 Stage 3: 600,dandelion,Light level of at least 12.
9,Eating Plant,Hasudako,NaN,Cactus,6,"Bad, Food",6,1,Stages 1-5: 1200 Grows 1.5x faster in swamp or...,eatingplant,Requires Lava (can be flow block) underneath f...
10,Ferru,IC2 Team,NaN,Ferru Leaves (for Iron),6,"Gray, Leaves, Metal",4,2,Stages 1-2: 800 Stage 3: 2000,ferru,Requires Iron Ore (Vanilla) or Block of Iron u...
11,Hops,IC2 Team,NaN,Hops,5,"Green, Ingredient, Wheat",7,3,Stages 1-6: 600,hops,Light level of at least 9.
12,Melon,Chao,Melon Seeds,"Melon(Item), Melon(Block)",2,"Green, Food, Stem",4,3,Stages 1-2: 250 Stage 3: 700,melon,NaN
13,Nether Wart,Notch,Nether Wart,Nether Wart,5,"Red, Nether, Ingredient, Soulsand",3,1,Stages 1-2: 1000,netherWart,Grows faster with Soul Sand under it. Turns in...
14,Plumbiscus,IC2 Team,NaN,Tiny Pile of Lead Dust,6,"Dense, Leaves, Metal",4,2,Stages 1-2: 800 Stage 3: 2000,plumbiscus,Requires Lead Block underneath farm block to f...
15,Potato,IC2 Team,Potato,"Potato, Poisonous Potato",2,"Yellow, Food, Potato",4,1,Stages 1-3: 400,potato,Light level of at least 9. Must be harvested e...
16,Pumpkin,Notch,Pumpkin Seeds,Pumpkin,1,"Orange, Decoration, Stem",4,3,Stages 1-2: 200 Stage 3: 600,pumpkin,NaN
17,Red Mushroom,IC2 Team,NaN,Mushroom (Red),2,"Red, Food, Mushroom",3,1,Stages 1-2: 200,Red Mushrooms,Must be hydrated.
18,Redwheat,raa1337,NaN,"Redstone, Wheat",6,"Red, Redstone, Wheat",7,2,Stages 1-6: 600,redwheat,Light level between 5 and 10 inclusive. May dr...
19,Reed,Notch,Sugar Canes,Sugar Canes,2,Reed,3,1,Stages 1-2: 200,reed,Harvestable early.
20,Rose,Notch,Poppyx4,Rose Red,2,"Red, Flower, Rose",4,3,Stages 1-2: 400 Stage 3: 600,rose,Light level of at least 12. Other vanilla flow...
21,Shining,IC2 Team,NaN,Tiny Pile of Silver Dust,8,"Silver, Leaves, Metal",5,2,Stages 1-3: 750 Stage 4: 2200,shining,NaN
22,Stagnium,IC2 Team,NaN,Tiny Pile of Tin Dust,6,"Shiny, Leaves, Metal",4,2,Stages 1-2: 800 Stage 3: 2000,stagnium,Requires Tin Block underneath farm block to fu...
23,Stickreed,raa1337,NaN,"Sugar Canes, Sticky Resin",4,"Reed, Resin",4,1/2/3,Stages 1-3: 100,stickreed,Drops Sticky Resin only when mature. Drops Sug...
24,Terra Wart,IC2 Team,Terra Wart,Terra Wart,5,"Blue, Aether, Consumable, Snow",3,1,Stages 1-2: 1000,terraWart,Grows faster with Snow under it. Turns into Ne...
25,Tulip,Alblaka,NaN,Purple Dye,2,"Purple, Flower, Tulip",4,3,Stages 1-2: 400 Stage 3: 600,tulip,Light level of at least 12.
26,Venomilia,raGan,NaN,Purple Dye/Grin Powder,3,"Purple, Flower, Tulip, Poison",6,3,Stages 1-2: 400 Stages 3-5: 600,venomilia,Light level of at least 12. Only drops Grin Po...
27,Weed,IC2 Crop,NaN,Weed,0,"Weed, Bad",5,-,Stages 1-4: 300,weed,Can only be harvested with Weeding Trowel or S...
28,Wheat,Notch,Seeds (Wheat),Wheat,1,"Yellow, Food, Wheat",7,2,Stages 1-6: 200,wheat,Light level of at least 9.

In [33]:
tables[1]

,Name,Discovered By,Seed,Drops,Tier,Attributes,Growth Stages,GS After Harvest,Relative Speed,Internal Name,Notes
0,Argentia,Eloraam,NaN,Argentia Leaf (for Silver),7,"Shiny, Metal, Silver, Reed",4,3,Stages 1-3: 1400,Argentia,Requires Silver Ore or Block of Silver underne...
1,Bauxia,unknown,NaN,Bauxia Leaf,6,"Metal, Aluminium, Reed, Aluminium",3,2,Stages 1-2: 1200,Bauxia,Requires Aluminium Ore or Block of Aluminium (...
2,Blazereed,Mr. Brain,NaN,"Blaze Powder, Blaze Rods",6,"Fire, Blaze, Reed, Sulfur",4,1,Stages 1-3: 1200,Blazereed,NaN
3,Bobsyeruncleranks,GenerikB,NaN,"Bobs-Yer-Uncle-Berry (for Emerald), Emerald",11,"Shiny, Tendrilly, Emerald, Berylium, Crystal",4,1,Stages 1-3: 2200,Bobsyeruncleranks,Requires Emerald Ore or Block of Emerald under...
4,Brown Mushrooms,Mr. Brain,4x Brown Mushrooms,Brown Mushroom,1,"Food, Mushroom, Ingredient",3,1,Stages 1-2: 200,Brown Mushrooms,NaN
5,Chilly,unknown,NaN,Chilly (causes Nausea),4,"Food, Red, Spicy",4,1,Stages 1-3: 800,Chilly,NaN
6,Coppon,Mr. Brain,NaN,Coppon Fiber (for Copper),6,"Shiny, Metal, Cotton, Copper, Bush",3,2,Stages 1-2: 1200,Coppon,Requires Copper Ore or Copper Block underneath...
7,Corium,Gregorius Techneticies,NaN,Leather,6,"Cow, Silk, Tendrilly",4,1,Stages 1-3: 1200,Corium,NaN
8,Corpseplant,Mr. Kenny,NaN,"Rotten Flesh, Bone Meal, Bone",5,"Toxic, Undead, Tendrilly, Food, Rotten",4,1,Stages 1-3: 1000,Corpseplant,NaN
9,Creeperweed,General Spaz,NaN,Gunpowder,7,"Creeper, Tendrilly, Explosive, Fire, Sulfur, S...",4,1,Stages 1-3: 1400,Creeperweed,NaN
10,Cucumber,unknown,NaN,Cucumber,4,"Food, Green",4,1,Stages 1-3: 800,Cucumber,NaN
11,Diareed,Direwolf20,NaN,"Tiny Pile of Diamond Dust, Diamond",12,"Fire, Shiny, Reed, Coal, Diamond, Crystal",4,1,Stages 1-3: 2400,Diareed,Requires Diamond Ore or Block of Diamond under...
12,Eggplant,Link,NaN,"Eggs, Chicken, Feather",6,"Chicken, Egg, Food, Feather, Flower, Addictive",3,2,Stages 1-2: 1200,Eggplant,NaN
13,Enderbloom,RichardG,NaN,"Ender Pearl Dust, Ender Pearl, Eye of Ender",10,"Ender, Flower, Shiny",4,1,Stages 1-3: 2000,Enderbloom,NaN
14,Evil Ore,unknown,NaN,"Tiny Pile of Nether Quartz Dust, Nether Quartz...",8,"Crystal, Fire, Nether",4,3,Stages 1-3: 1600,Evil Ore,NaN
15,Fertilia,unknown,NaN,"Tiny Pile of Calcite Dust, Phosphate Dust, Fer...",3,"Growth, Healing, Flower",4,1,Stages 1-3: 600,Fertilia,Can be bred from Zomplant.
16,Flax,Eloraam,NaN,String,2,"Silk, Tendrilly, Addictive",4,1,Stages 1-3: 400,Flax,NaN
17,Galvania,unknown,NaN,Galvania Leaf (for Zinc),6,"Metal, Alloy, Bush",3,2,Stages 1-2: 1200,Galvania,Requires Block of Zinc underneath farm block t...
18,Glowheat,unknown,NaN,Tiny Pile of Glowstone Dust,10,"Light, Shiny, Crystal",7,5,Stages 1-6: 2000,Glowheat,Other Glowstone options are better.
19,God of Thunder,unknown,NaN,Thunder Leaf (for Thorium),9,"Radioactive, Metal, Coal, Thorium",4,2,Stages 1-3: 1800,God of Thunder,Requires Thorium Ore or Block of Thorium under...
20,Grape,unknown,NaN,Grape,4,"Food, Purple",4,1,Stages 1-3: 800,Grape,NaN
21,Indigo,Eloraam,4x Indigo Blossom,Indigo Blossom,2,"Flower, Blue, Ingredient",4,1,Stages 1-3: 400,Indigo,NaN
22,Lazulia,unknown,NaN,Tiny Pile of Lapis Dust,7,"Shiny, Bad, Crystal, Lapis",4,2,Stages 1-3: 1400,Lazulia,Requires Lapis Ore or Block of Lapis underneat...
23,Lemon,unknown,NaN,Lemon,4,"Food, Yellow, Sour",4,1,Stages 1-3: 800,Lemon,NaN
24,Liveroots,Benimatic,NaN,"Liveroots Powder, Liveroots",8,"Wood, Tendrilly",4,1,Stages 1-3: 1600,Liveroots,NaN
25,Meatrose,VintageBeef,NaN,"Pink Dye, Fish, every raw vanilla meat",7,"Food, Flower, Cow, Fish, Chicken, Pig",4,1,Stages 1-3: 1400,Meatrose,NaN
26,Micadia,bartimaeusnek,NaN,Micadia Twig (for Mica),9,"Metal, Pine, Mica, Bush",3,2,Stages 1-2: 1800,Micadia,Requires Mica Ore underneath farm block to ful...
27,Milkwart,Mr. Brain,4x Milkwart,Milk Wart,6,"Food, Milk, Cow",3,1,Stages 1-2: 1200,Milkwart,Put in Fluid extractor for 150L Milk each and ...
28,Nickelback,unknown,NaN,Nickelback Leaf (for Nickel),5,"Metal, Fire, Alloy",3,2,Stages 1-2: 1000,Nickelback,Requires Nickel Ore or Block of Nickel underne...
29,Oilberries,Spacetoad,NaN,Oil Berry,9,"Fire, Dark, Reed, Rotten, Coal, Oil",4,1,Stages 1-3: 1800,Oilberries,Fluid extract for 100L Oil.
30,Olivia,unknown,NaN,"Tiny Pile of Olivine Dust, Olivine",2,"Crystal, Shiny, Processing, Olivine",4,3,Stages 1-3: 400,Olivia,Requires Olivine Ore or Block of Olivine under...
31,Onion,unknown,NaN,Onion,4,"Food, Brown",4,1,Stages 1-3: 800,Onion,NaN
32,Platina,unknown,NaN,Platina Leaf (for Platinum),11,"Metal, Shiny, Reed, Platinum",4,1,Stages 1-3: 2200,Platina,Requires Platinum Ore or Block of Platinum und...
33,Plumbilia,KingLemming,NaN,Plumbilia Leaf (for Lead),6,"Heavy, Metal, Lead, Reed",4,3,Stages 1-3: 1200,Plumbilia,Requires Lead Ore or Lead Block underneath far...
34,Pyrolusium,unknown,NaN,Pyrolusium Leaf,12,"Metal, Clean, Bush, Manganese",3,2,Stages 1-2: 2400,Pyrolusium,Requires Manganese Ore or Block of Manganese u...
35,Quantaria,unknown,NaN,"Quantaria Leaf (Iridium), Quantaria Leaf (Osmium)",12,"Metal, Iridium, Reed",4,1,Stages 1-3: 2400,Quantaria,Requires Iridium Ore or Block of Iridium under...
36,Rape(seed),unknown,NaN,Rape (Flower),4,"Food, Yellow, Oil",4,1,Stages 1-3: 800,Rape,Fluid extract for 125L Seed Oil each.
37,Reactoria,unknown,NaN,"Reactoria Leaf (for Pitchblende), Uranium Leaf...",12,"Radioactive, Metal, Danger, Uranium",4,2,Stages 1-3: 2400,Reactoria,"Requires Uranium Ore, Uranium 238 Ore, Uranium..."
38,Red Mushrooms,Mr. Kenny,4x Red Mushrooms,Red Mushroom,1,"Toxic, Mushroom, Ingredient",3,1,Stages 1-2: 200,Red Mushrooms,NaN
39,Sapphirum,unknown,NaN,"Tiny Pile of Sapphire Dust, Sapphire",4,"Crystal, Shiny, Metal, Sapphire",4,3,Stages 1-3: 800,Sapphirum,Requires Sapphire Ore or Block of Sapphire (Bl...
40,Scheelinium,unknown,NaN,Scheelinium Leaf (for Tungsten),12,"Metal, Hard, Bush, Tungsten",3,2,Stages 1-2: 2400,Scheelinium,Requires Tungsten Ore or Block of Tungsten und...
41,Slimeplant,Neowulf,NaN,Slimeball,6,"Slime, Bouncy, Sticky, Bush",4,3,Stages 1-3: 1200,Slimeplant,NaN
42,Spidernip,Mr. Kenny,NaN,"String, Spider Eye, Cobweb",4,"Toxic, Silk, Spider, Flower, Ingredient, Addic...",4,1,Stages 1-3: 800,Spidernip,NaN
43,Stargatium,unknown,NaN,"Stargatium Leaf (for Naquadah), Endstone Dust",12,"Metal, Heavy, Alien, Naquadah",4,1,Stages 1-3: 2400,Stargatium,Requires Naquadah Ore or Block of Naquadah und...
44,Starwart,unknown,NaN,"Small Pile of Coal Dust, Wither Skeleton Skull...",12,"Wither, Nether, Undead, Netherstar",4,1,Stages 1-3: 2400,Starwart,Requires Nether Star Ore or Block of Nether St...
45,Steeleafranks,Benimatic,NaN,"Steeleaf Dust, Steeleaf",10,"Metal, Tendrilly, Iron",4,1,Stages 1-3: 2000,Steeleafranks,NaN
46,Tea,unknown,NaN,Tea,4,"Food, Green, Ingredient",4,1,Stages 1-3: 800,Tea,NaN
47,Tearstalks,Neowulf,NaN,Ghast Tear,8,"Healing, Nether, Ingredient, Reed, Ghast",4,1,Stages 1-3: 1600,Tearstalks,NaN
48,Tine,Gregorius Techneticies,NaN,Tine Twig (for Tin),5,"Shiny, Metal, Pine, Tin, Bush",3,2,Stages 1-2: 1000,Tine,Requires Tin Ore or Tin Block underneath farm ...
49,Titania,unknown,NaN,Titania Leaf (for Titanium),9,"Metal, Heavy, Reed, Titanium",3,2,Stages 1-2: 1800,Titania,Requires Titanium Ore or Block of Titanium und...
50,Tomato,unknown,NaN,"Tomato, MaxiTomato (Restores health)",4,"Food, Red",4,1,Stages 1-3: 800,Tomato,NaN
51,Transformium,unknown,NaN,"UUA Berry, UUM Berry",12,"Transform, Coal, Reed",4,1,Stages 1-3: 2400,Transformium,NaN
52,Trollplant,unknown,NaN,"Ruby (Fake), Scrap, Plantball, Tiny Pile of Pl...",6,"Troll, Bad, Scrap",5,1,Stages 1-4: 1200,Trollplant,"Plutonium-241 is radioactive, so a Hazmat Suit..."
53,Withereed,CovertJaguar,NaN,"Coal Dust, Coal",8,"Fire, Undead, Reed, Coal, Rotten, Wither",4,1,Stages 1-3: 1600,Withereed,Requires Coal Ore or Block of Coal underneath ...
54,Zomplant,unknown,NaN,Rotten Flesh,3,"Zombie, Rotten, Undead",4,1,Stages 1-3: 600,Zomplant,NaN

In [35]:
df = pd.concat([tables[0], tables[1]], ignore_index=True, sort=False)

In [36]:
df

,Name,Discovered By,Seed,Drops,Tier,Attributes,Growth Stages,GS After Harvest,Relative Speed,Internal Name,Notes
0,Aurelia,IC2 Team,NaN,Aurelia Leaves (for Gold),8,"Gold, Leaves, Metal",5,2,Stages 1-3: 750 Stage 4: 2200,aurelia,Requires Gold Ore (Vanilla) or Block of Gold u...
1,Blackthorn,Alblaka,NaN,Ink Sac,2,"Black, Flower, Rose",4,3,Stages 1-2: 400 Stage 3: 600,blackthorn,Light level of at least 12.
2,Brown Mushroom,IC2 Team,NaN,Mushroom (Brown),2,"Brown, Food, Mushroom",3,1,Stages 1-2: 200,Brown Mushrooms,Must be hydrated.
3,Carrots,IC2 Team,Carrots,Carrots,2,"Orange, Food, Carrots",3,1,Stages 1-2: 400,carrots,Light level of at least 12.
4,Cocoa,Notch,Cocoa,Cocoa,3,"Brown, Food, Stem",4,3,Stages 1-2: 400 Stage 3: 900,cocoa,Nutrients of at least 3.
...,...,...,...,...,...,...,...,...,...,...,...
79,Tomato,unknown,NaN,"Tomato, MaxiTomato (Restores health)",4,"Food, Red",4,1,Stages 1-3: 800,Tomato,NaN
80,Transformium,unknown,NaN,"UUA Berry, UUM Berry",12,"Transform, Coal, Reed",4,1,Stages 1-3: 2400,Transformium,NaN
81,Trollplant,unknown,NaN,"Ruby (Fake), Scrap, Plantball, Tiny Pile of Pl...",6,"Troll, Bad, Scrap",5,1,Stages 1-4: 1200,Trollplant,"Plutonium-241 is radioactive, so a Hazmat Suit..."
82,Withereed,CovertJaguar,NaN,"Coal Dust, Coal",8,"Fire, Undead, Reed, Coal, Rotten, Wither",4,1,Stages 1-3: 1600,Withereed,Requires Coal Ore or Block of Coal underneath ...
83,Zomplant,unknown,NaN,Rotten Flesh,3,"Zombie, Rotten, Undead",4,1,Stages 1-3: 600,Zomplant,NaN

In [37]:
from pathlib import Path

In [40]:
basedir = Path().resolve()

basedir

PosixPath('/home/art/dev/github/GT-crops-helper/src/utils/build_csv')

In [54]:
tables[0].to_csv(basedir / "ic2_gtnh_data.csv", sep=";", index=False)

In [55]:
tables[1].to_csv(basedir / "gregtech_gtnh_data.csv", sep=";", index=False)